/* Drop the tables */
DROP TABLE IF EXISTS generic_log_event CASCADE;
DROP TABLE IF EXISTS portfolio_log_event CASCADE;
DROP TABLE IF EXISTS account_log_event CASCADE;
DROP TABLE IF EXISTS log_event CASCADE;
DROP TABLE IF EXISTS held_share CASCADE;
DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS purchase CASCADE;
DROP TABLE IF EXISTS stock_transaction CASCADE;
DROP TABLE IF EXISTS historical_stock_price CASCADE;
DROP TABLE IF EXISTS stock CASCADE;
DROP TABLE IF EXISTS auth_session CASCADE;
DROP TABLE IF EXISTS portfolio CASCADE;
DROP TABLE IF EXISTS account CASCADE;